// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ce0kj6_ptok1ZJjI1ol1kClvQchEG3o',
    appId: '1:819765074466:web:9c564e8856694ba3eb087b',
    messagingSenderId: '819765074466',
    projectId: 'practicamoviles-6794f',
    authDomain: 'practicamoviles-6794f.firebaseapp.com',
    storageBucket: 'practicamoviles-6794f.firebasestorage.app',
    measurementId: 'G-DCFH12Q8PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPyaVJ94pq5sT3vAvhYpHArmLSPex9pq4',
    appId: '1:819765074466:android:97df8dde47cb1d00eb087b',
    messagingSenderId: '819765074466',
    projectId: 'practicamoviles-6794f',
    storageBucket: 'practicamoviles-6794f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7qrmo742sPnpe9WAtNRaP4ikB3dyv_Us',
    appId: '1:819765074466:ios:b80bb7bd221c897eeb087b',
    messagingSenderId: '819765074466',
    projectId: 'practicamoviles-6794f',
    storageBucket: 'practicamoviles-6794f.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7qrmo742sPnpe9WAtNRaP4ikB3dyv_Us',
    appId: '1:819765074466:ios:b80bb7bd221c897eeb087b',
    messagingSenderId: '819765074466',
    projectId: 'practicamoviles-6794f',
    storageBucket: 'practicamoviles-6794f.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Ce0kj6_ptok1ZJjI1ol1kClvQchEG3o',
    appId: '1:819765074466:web:6d1d6e870f36ce07eb087b',
    messagingSenderId: '819765074466',
    projectId: 'practicamoviles-6794f',
    authDomain: 'practicamoviles-6794f.firebaseapp.com',
    storageBucket: 'practicamoviles-6794f.firebasestorage.app',
    measurementId: 'G-2XL71THM7X',
  );
}
